### PR TITLE
README: mention the need for the `hungarian` module

### PR DESCRIPTION
**Pull request by dscho**
It is easy for Python experts to know what to do about this error:

```
ImportError: No module named hungarian
```

Everybody else will appreciate a little help. So let's give it.

Signed-off-by: Johannes Schindelin johannes.schindelin@gmx.de

### CODE REVIEW

**Comment by dscho** [comment]
@trast Ping???

**Comment by dscho** [comment]
@trast are you alive or what????

**Comment by tsibley** [comment]
I've merged this PR into my fork: https://github.com/tsibley/git-tbdiff

Thanks for the patch!

**Comment by dscho** [comment]
my-give-up

**Pull request closed without merging**
